export type dateFormat =
  // year month
  | "YY M"
  | "YY/M"
  | "YY-M"
  | "YY MM"
  | "YY/MM"
  | "YY-MM"
  | "YY MMM"
  | "YY/MMM"
  | "YY-MMM"
  | "YY MMMM"
  | "YY/MMMM"
  | "YY-MMMM"
  | "YYYY M"
  | "YYYY/M"
  | "YYYY-M"
  | "YYYY MM"
  | "YYYY/MM"
  | "YYYY-MM"
  | "YYYY MMM"
  | "YYYY/MMM"
  | "YYYY-MMM"
  | "YYYY MMMM"
  | "YYYY/MMMM"
  | "YYYY-MMMM"
  // month  year
  | "M YY"
  | "M/YY"
  | "M-YY"
  | "MM YY"
  | "MM/YY"
  | "MM-YY"
  | "MMM YY"
  | "MMM/YY"
  | "MMM-YY"
  | "MMMM YY"
  | "MMMM/YY"
  | "MMMM-YY"
  | "M YYYY"
  | "M/YYYY"
  | "M-YYYY"
  | "MM YYYY"
  | "MM/YYYY"
  | "MM-YYYY"
  | "MMM YYYY"
  | "MMM/YYYY"
  | "MMM-YYYY"
  | "MMMM YYYY"
  | "MMMM/YYYY"
  | "MMMM-YYYY"
  // day month year
  | "D M YY"
  | "DD MM YY"
  | "D MMM YY"
  | "D MMMM YY"
  | "DD M YYYY"
  | "DD MM YYYY"
  | "D MMM YYYY"
  | "D MMMM YYYY"
  | "MMM D YYYY"
  | "MMMM D YYYY"
  | "MMM DD YYYY"
  | "MMMM DD YYYY"
  | "MMM D, YYYY"
  | "MMMM D, YYYY";
